### ISSUE TITLE
Training on own model

### ISSUE THREAD

**Issue by ciuhc** [declare-lab/tango#16]
Hi, amazing work all!
From what I understand it is possible to train the model on my own data. I've got a sound library, which I want to use to train the model. Do I just replace the .json elements in the data folder?

/Update:
I replaced the data folder json's with mine and after some back and forth I'm stick at the following error. Of course the columns match:

> _ValueError: Couldn't cast
> dataset: string
> location: string
> to
> {'dataset': Value(dtype='string', id=None), 'location': Value(dtype='string', id=None), 'captions': Value(dtype='string', id=None)}
> because column names don't match_

Perhapse the issue is how the file is made? I pulled he metadata into xlsx -> made python script to make json and did some formatting fixes.

thx!

Ps. how big is your training setup in terms of GPU's?

**Comment by deepanwayx** [comment]
```bash
ValueError: Couldn't cast
dataset: string
location: string
```

This doesn't have the `captions` field. That's why the column names do not match. Perhaps you could use some metadata about your audio clips as `captions`? TANGO needs some captions as input on which it conditions the generated outputs.

We used a 4* RTX A 6000 for training.

**Comment by ciuhc** [comment]
Seems like it was having issues with the json file - when I made a csv it worked fine. Probably something with the json creation script.
Thanks!
