### ISSUE TITLE
Nan loss in training

### ISSUE THREAD

**Issue by tranquangchung** [declare-lab/tango#17]
Hi
Thanks for sharing your project.
When I trained your model based on your config, however, the val and train loss was NAN.
I tried many times but the results are still the same. 
Can you tell me the reasons and how to solve it?

**Comment by Sreyan88** [comment]
Hi @tranquangchung , How did you solve the nan problem? Thank You!

**Comment by BingliangLi** [comment]
Hi, could you please explain how do you solve this problem? Thx!

**Comment by BingliangLi** [comment]
It turns out the problem is with google/flan-t5-large, this model does not support fp16 training, use fp32 it would be fine.

**Comment by soujanyaporia** [comment]
Glad to know that it was solved. FYI we have released Tango 2: https://arxiv.org/abs/2404.09956
