### ISSUE TITLE
HOW MUCH VRAM IS REQUIRED FOR INFERENCE?

### ISSUE THREAD

**Issue by illtellyoulater** [declare-lab/tango#27]
Hello, could you please tell us how many VRAM GB are required for inference?
Thank you!

**Comment by deepanwayx** [comment]
The required VRAM is around 13GB for full precision inference with a batch size of 1

**Comment by illtellyoulater** [comment]
@deepanwayx  It would be great if it could be lowered to 12 GB in order to make tango available to all those GPUs coming in that format.
Do you think it's possible?
