### ISSUE TITLE
HF Space seems to be down?

### ISSUE THREAD

**Issue by regstuff** [declare-lab/tango#4]
GEtting a 404 for this - https://huggingface.co/spaces/declare-lab/tango-text-to-audio-generation
Was it taken down?

**Comment by soujanyaporia** [comment]
We have not yet made it public.

**Comment by soujanyaporia** [comment]
Here is the link to the space: https://huggingface.co/spaces/declare-lab/tango. We requested for GPU community grant to HF. For now, we have no choice but to run it on the CPU.
