### ISSUE TITLE
Classifier-free guidance(CFG) in training vs inference

### ISSUE THREAD

**Issue by sakshamsingh1** [declare-lab/tango#42]
Thanks for the awesome code. 

If I am not wrong, the CFG implementation during training and inference seems to have some inconsitency.

During training, the unconditioned text-embedding is set to 0
```
mask_indices = [k for k in range(len(prompt)) if random.random() < 0.1]
if len(mask_indices) > 0:
    encoder_hidden_states[mask_indices] = 0
```

While during inference, an empty prompt is used for the text-unconditioning
```
uncond_tokens = [""] * len(prompt)
```

Are these two ways equivalent? Or am I missing something?

**Comment by deepanwayx** [comment]
We [did not use the uncondition flag during training](https://github.com/declare-lab/tango/blob/master/train.sh) for the released models. 

Thanks for the catch though. I think I might have overlooked this while writing the code. If we were to use CFG during training, then using the empty prompt embedding would have been more appropriate.
