### ISSUE TITLE
Preview and save multiple samples of the same prompt

### ISSUE THREAD

**Issue by esuriddick** [declare-lab/tango#45]
Hi,

I see in the model's page that you can generate multiple samples for the same prompt using, for example:
prompts = [
"A car engine revving",
"A dog barks and rustles with some clicking",
"Water flowing and trickling"
]
audios = tango.generate_for_batch(prompts, samples=2)

This will create two samples per prompt, so audios will comprise 2 sounds per prompt.

How do you preview the sounds and then save the one you want? I've tried using indexes, but to no success.

Regards,
esuriddick

**Comment by deepanwayx** [comment]
The generated audios are returned as a list of list for `samples > 1` as you can see here in the [`generate_for_batch`](https://github.com/declare-lab/tango/blob/master/tango.py#L64) function.

It should be accessible through indices as follows:

```python
import IPython
import soundfile as sf
from tango import Tango

tango = Tango("declare-lab/tango2")

prompts = [
    "A car engine revving",
    "A dog barks and rustles with some clicking",
    "Water flowing and trickling"
]
audios = tango.generate_for_batch(prompts, samples=2)

prompt_index = 0 # use 0, 1 or 2 as there are a total of three prompts
index_to_preview = 0 # use 0 or 1 as two samples were generated for each prompt

audio = audios[prompt_index][index_to_preview]
IPython.display.Audio(data=audio, rate=16000)

sf.write(f"{prompts[prompt_index]}.wav", audio, samplerate=16000)

```

**Comment by esuriddick** [comment]
Your suggestion worked like a charm. My main issue was not understanding that a prompt_index was required!
