### ISSUE TITLE
Fine-Tuning TANGO 2

### ISSUE THREAD

**Issue by cvillela** [declare-lab/tango#50]
Hey all!
Congrats on the amazing project and for making it open-sourced.

I want to fine-tune tango2, the results are really impressive. 
I have a proprietary dataset of audio and text captions, but nothing in the Audio-Alpaca format...

How could one fine-tune tango 2 on those conditions?

thanks a lot

**Comment by soujanyaporia** [comment]
Hey!

Thanks. You may just run this: accelerate launch train.py \
--hf_model "declare-lab/tango2" \
--unet_model_config="configs/diffusion_model_config.json" \
--freeze_text_encoder --augment --snr_gamma 5 \

**Comment by cvillela** [comment]
@soujanyaporia thank you very much for the reply.

In this case would I need to train the model from scratch with Audiocaps + Alpaca + My dataset?
Or is it pulling the tango2 checkpoint and would just finetune the trained over my new `train.json` file?

**Comment by soujanyaporia** [comment]
is it pulling the tango2 checkpoint and would just finetune the trained over my new train.json file?

> Yes!

Same goes for the valid_audiocaps.json and test_audiocaps_subset.json files: do I need to replace them with my own dataset files?

> Yes, you can but not necessary.

And souldn't I be running [tango2-train.py](https://github.com/declare-lab/tango/blob/master/tango2/tango2-train.py) instead?

> No! because tango2 is trained using DPO. For fine-tuning, you do not need that.

**Comment by cvillela** [comment]
Thank you very much for your help, I will be closing the issue!

One other question would be, how many hours of recordings would you deem necessary for finetuning? 
I know this could be subjective depending on the task at hand, but any estimates would be much appreciated.
