### ISSUE TITLE
Update Requirement infos (ipython, libsndfile1)

### ISSUE THREAD

**Issue by HansRandomizer** [declare-lab/tango#7]
Congratulation for your great project!

After going through your instructions, I found that I needed to install IPython manually. Please consider adding ipython to the requirement list.

Additionally, for _soundfile_ to function properly (at least on Linux in my case), libsndfile1 is necessary. Maybe you also want to add this to the prerequisites documentation:
`(sudo) apt-get install libsndfile1`

**Comment by deepanwayx** [comment]
Thanks for letting us know. Have added them to the requirements and ReadMe now.

**Comment by trholding** [comment]
@deepanwayx you can add diffusers to requirements.txt, that way one doesn't need to install the version in this repo

**Comment by deepanwayx** [comment]
We made some changes in the UNet class of diffusers so that it uses attention masking on the encoded text vectors. As of now directly doing `pip install diffusers` won't have this functionality and will break tango.
