### ISSUE TITLE
Inference on server without GPU

### ISSUE THREAD

**Issue by trholding** [declare-lab/tango#8]
Cuda is required for this to work. Can you enable cpu inference on server. I know it could be slow, but I don't mind the wait for experimentation purpose.

**Comment by deepanwayx** [comment]
You can use `tango = Tango("declare-lab/tango", "cpu")`

**Comment by trholding** [comment]
Apologies, my mistake, I didn't use the local diffusers (https://github.com/declare-lab/tango/issues/7#issuecomment-1528973434) and I had edited tango.py to use cpu globally, I think that's what broke it. After reverting and using 

```tango = Tango("declare-lab/tango", "cpu")```

inference is working on the arm server. Seems like it will take a long time without GPU.
